---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      enableServiceLinks: false
      containers:
      - name: rest-server
        image: "rest_server:0.1"
        imagePullPolicy: IfNotPresent
# Liveness and Readiness probes checks should be different as they serve a different purpose but in this case there is only one rest api call available
# Liveness probe helps in triggering kubelet to restart the container
        livenessProbe:
          httpGet:
            path: /tree
            port: 1234
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
# Readiness probe helps kube-proxy in deciding if the container is ready to accept traffic
        readinessProbe:
          httpGet:
            path: /tree
            port: 1234
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
        env:
          - name: GUNICORN_WORKERS
            value: "2"
        ports:
          - containerPort: 1234
